/**
 * Regenerates the local stack's baseline from production.
 *
 * A schema-only dump of `lumen`, reconstructed from the catalog via
 * pg_get_*def() rather than pg_dump — no client-version pinning to keep in
 * step with whatever Postgres Supabase runs, and no libpq on the box.
 * Reads the admin DSN; writes supabase/migrations/<baseline>.sql.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(join(ROOT, "package.json"));
const { Client } = require("pg");

// admin DSN, same sourcing rule as e2e/support/global-setup.ts
const dsn =
	process.env.DATABASE_URL ??
	readFileSync(join(ROOT, ".env"), "utf8")
		.match(/^DATABASE_URL=(.+)$/m)?.[1]
		?.trim();
if (!dsn) throw new Error("no DATABASE_URL (env or repo-root .env)");
const c = new Client({ connectionString: dsn });
await c.connect();
const rows = async (sql, p) => (await c.query(sql, p)).rows;

const out = [];
const w = (s = "") => out.push(s);

w("-- Baseline schema for the lumen local stack.");
w("-- Generated from production by scripts/dump-schema.mjs — do not hand-edit;");
w("-- regenerate instead so local can never silently drift from prod.");
w("-- Excludes: auth/storage/realtime/vault (Supabase provisions those itself).");
w();

w("-- ── extensions ─────────────────────────────────────────────");
for (const e of await rows(`
  select e.extname, n.nspname from pg_extension e
  join pg_namespace n on n.oid=e.extnamespace
  where e.extname not in ('plpgsql','supabase_vault','pg_stat_statements')
  order by 1`)) {
	w(`create extension if not exists "${e.extname}" with schema ${e.nspname};`);
}
w();

w("-- ── schema + roles ─────────────────────────────────────────");
w("create schema if not exists lumen;");
w(`-- the app's SELECT-only production credential; recreated locally so GRANTs below resolve
do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'lumen_read') then
    create role lumen_read login password 'lumen_read';
  end if;
end $$;`);
w();

// ── tables ────────────────────────────────────────────────────
const tables = await rows(`
  select c.oid, c.relname, c.relrowsecurity as rls
  from pg_class c join pg_namespace n on n.oid=c.relnamespace
  where c.relkind in ('r','p') and n.nspname='lumen'
  order by c.relname`);

w("-- ── tables ─────────────────────────────────────────────────");
for (const t of tables) {
	const cols = await rows(
		`select a.attname,
            format_type(a.atttypid, a.atttypmod) as type,
            a.attnotnull as notnull,
            pg_get_expr(d.adbin, d.adrelid) as def,
            a.attidentity as identity,
            a.attgenerated as generated
     from pg_attribute a
     left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum
     where a.attrelid=$1 and a.attnum>0 and not a.attisdropped
     order by a.attnum`,
		[t.oid],
	);
	w(`create table if not exists lumen.${t.relname} (`);
	const lines = cols.map((col) => {
		let s = `  ${col.attname} ${col.type}`;
		if (col.identity === "a") s += " generated always as identity";
		else if (col.identity === "d") s += " generated by default as identity";
		else if (col.generated === "s") s += ` generated always as (${col.def}) stored`;
		else if (col.def !== null) s += ` default ${col.def}`;
		if (col.notnull) s += " not null";
		return s;
	});
	w(lines.join(",\n"));
	w(");");
}
w();

w("-- ── constraints ────────────────────────────────────────────");
// Two GLOBAL passes, not per-table ones: every primary/unique/check across all
// tables, then every foreign key. An FK is only creatable once its target's
// unique constraint exists, and targets are not in alphabetical order —
// books.volume_id → volumes(id) fails if books is finished before volumes starts.
for (const pass of [["p", "u", "c"], ["f"]]) {
	for (const t of tables) {
		for (const k of await rows(
			`select conname, pg_get_constraintdef(oid) as def
       from pg_constraint where conrelid=$1 and contype = any($2::char[])
       order by conname`,
			[t.oid, pass],
		)) {
			w(`alter table lumen.${t.relname} add constraint ${k.conname} ${k.def};`);
		}
	}
}
w();

w("-- ── views ──────────────────────────────────────────────────");
for (const v of await rows(`
  select c.relname, c.relkind, pg_get_viewdef(c.oid, true) as def, c.reloptions
  from pg_class c join pg_namespace n on n.oid=c.relnamespace
  where n.nspname='lumen' and c.relkind in ('v','m')
  order by c.relkind, c.relname`)) {
	const kind = v.relkind === "m" ? "materialized view" : "view";
	const opts = v.reloptions?.length ? ` with (${v.reloptions.join(", ")})` : "";
	w(`create or replace ${kind} lumen.${v.relname}${opts} as`);
	w(v.def.trim());
	w();
}

w("-- ── indexes ────────────────────────────────────────────────");
for (const i of await rows(`
  select indexdef from pg_indexes where schemaname='lumen'
  and indexname not in (
    select conname from pg_constraint where contype in ('p','u')
  ) order by tablename, indexname`)) {
	w(`${i.indexdef};`);
}
w();

w("-- ── functions ──────────────────────────────────────────────");
for (const f of await rows(`
  select pg_get_functiondef(p.oid) as def
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='lumen' order by p.proname`)) {
	w(`${f.def};`);
	w();
}

w("-- ── triggers ───────────────────────────────────────────────");
for (const t of await rows(`
  select pg_get_triggerdef(tg.oid) as def
  from pg_trigger tg
  join pg_class c on c.oid=tg.tgrelid
  join pg_namespace n on n.oid=c.relnamespace
  where n.nspname='lumen' and not tg.tgisinternal
  order by c.relname, tg.tgname`)) {
	w(`${t.def};`);
}
w();

w("-- ── row level security ─────────────────────────────────────");
for (const t of tables.filter((t) => t.rls)) {
	w(`alter table lumen.${t.relname} enable row level security;`);
}
w();
for (const p of await rows(`
  select schemaname, tablename, policyname, permissive, roles, cmd, qual, with_check
  from pg_policies where schemaname='lumen'
  order by tablename, policyname`)) {
	// pg_policies.roles is name[]; node-pg has no parser for it and hands back
	// the raw literal `{anon,authenticated}` rather than an array
	const roles = (
		Array.isArray(p.roles) ? p.roles : String(p.roles).replace(/^\{|\}$/g, "").split(",")
	)
		.filter(Boolean)
		.join(", ");
	let s = `create policy "${p.policyname}" on lumen.${p.tablename}`;
	s += `\n  as ${p.permissive.toLowerCase()} for ${p.cmd.toLowerCase()} to ${roles}`;
	if (p.qual) s += `\n  using (${p.qual})`;
	if (p.with_check) s += `\n  with check (${p.with_check})`;
	w(`${s};`);
}
w();

w("-- ── grants ─────────────────────────────────────────────────");
w("grant usage on schema lumen to anon, authenticated, service_role, lumen_read;");
// Read the ACLs straight off pg_class rather than information_schema.
// role_table_grants is permission-FILTERED — it only reports grants visible to
// the connecting role, so the `authenticated` grants came back empty and the
// generated baseline silently omitted every INSERT/UPDATE/DELETE the app needs.
// The symptom was "permission denied for table notes" on the first write.
const grants = await rows(`
  select c.relname as table_name, g.grantee,
         string_agg(distinct g.privilege_type, ', ' order by g.privilege_type) as privs
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  cross join lateral aclexplode(coalesce(c.relacl, acldefault('r', c.relowner))) a
  cross join lateral (select pg_get_userbyid(a.grantee) as grantee, a.privilege_type) g
  where n.nspname = 'lumen' and c.relkind in ('r','p','v','m')
    and g.grantee in ('anon','authenticated','service_role','lumen_read')
  group by c.relname, g.grantee
  order by c.relname, g.grantee`);
for (const g of grants) {
	w(`grant ${g.privs.toLowerCase()} on lumen.${g.table_name} to ${g.grantee};`);
}
w();
// Column-level grants. Production deliberately narrows `authenticated` to
// specific columns — INSERT/UPDATE on notes.body_md, UPDATE on notes.deleted_at,
// INSERT on the four note_anchors columns — so a client cannot forge owner_id
// or touch timestamps. These live in pg_attribute.attacl, NOT pg_class.relacl;
// omitting them makes local strictly MORE permissive than production, which is
// the wrong direction for an environment that gates an autonomous agent.
const colGrants = await rows(`
  select c.relname as table_name, g.grantee, g.privilege_type,
         string_agg(a.attname, ', ' order by a.attnum) as cols
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  join pg_namespace n on n.oid = c.relnamespace
  cross join lateral aclexplode(a.attacl) ax
  cross join lateral (select pg_get_userbyid(ax.grantee) as grantee, ax.privilege_type) g
  where n.nspname = 'lumen' and a.attacl is not null
    and g.grantee in ('anon','authenticated','service_role','lumen_read')
  group by c.relname, g.grantee, g.privilege_type
  order by c.relname, g.grantee, g.privilege_type`);
for (const g of colGrants) {
	w(`grant ${g.privilege_type.toLowerCase()} (${g.cols}) on lumen.${g.table_name} to ${g.grantee};`);
}
if (colGrants.length) w();

for (const g of await rows(`
  select p.proname, pg_get_function_identity_arguments(p.oid) as args, a.grantee
  from pg_proc p
  join pg_namespace n on n.oid=p.pronamespace
  cross join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a_raw
  cross join lateral (select pg_get_userbyid(a_raw.grantee) as grantee, a_raw.privilege_type) a
  where n.nspname='lumen' and a.privilege_type='EXECUTE'
    and a.grantee in ('anon','authenticated','service_role')
  order by p.proname, a.grantee`)) {
	w(`grant execute on function lumen.${g.proname}(${g.args}) to ${g.grantee};`);
}

await c.end();

const path = join(ROOT, "supabase/migrations/20260801000000_baseline.sql");
writeFileSync(path, `${out.join("\n")}\n`);
console.log(`wrote ${path} — ${out.length} lines, ${tables.length} tables`);
