/**
 * Bridges the local Supabase stack into the app and the e2e suite.
 *
 * Three consumers need three different shapes of the same facts:
 *   - the Worker      reads SUPABASE_URL / SUPABASE_PUBLISHABLE_KEY from
 *                     apps/web/.dev.vars (which overrides wrangler.json vars)
 *   - the drizzle leg reads env.HYPERDRIVE.connectionString, which in local dev
 *                     comes from WRANGLER_HYPERDRIVE_LOCAL_CONNECTION_STRING_*
 *                     — a PROCESS env var, so it cannot live in .dev.vars
 *   - the suite       reads SUPABASE_URL / SUPABASE_PUBLISHABLE_KEY /
 *                     SUPABASE_SERVICE_ROLE_KEY / DATABASE_URL from process env
 *
 * Usage:
 *   node scripts/local-stack.mjs env    # KEY=VALUE lines for `eval`
 *   node scripts/local-stack.mjs write  # (re)write apps/web/.dev.vars
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const cmd = process.argv[2] ?? "env";

/** `supabase status -o env` — key names have drifted across CLI majors, so read
 *  whatever it emits and resolve by preference rather than assuming one name. */
function status() {
	let raw;
	try {
		raw = execFileSync("npx", ["--yes", "supabase", "status", "-o", "env"], {
			cwd: ROOT,
			encoding: "utf8",
			stdio: ["ignore", "pipe", "pipe"],
		});
	} catch (err) {
		const detail = (err.stderr || err.stdout || err.message).toString().trim();
		throw new Error(
			`supabase status failed — is the stack up? try \`pnpm db:start\`.\n${detail}`,
		);
	}
	const kv = {};
	for (const line of raw.split("\n")) {
		const m = line.match(/^([A-Z0-9_]+)\s*=\s*"?(.*?)"?\s*$/);
		if (m) kv[m[1]] = m[2];
	}
	return kv;
}

const pick = (kv, ...names) => names.map((n) => kv[n]).find((v) => v);

const kv = status();
const apiUrl = pick(kv, "API_URL", "SUPABASE_URL");
const anon = pick(kv, "ANON_KEY", "SUPABASE_ANON_KEY", "PUBLISHABLE_KEY");
const service = pick(kv, "SERVICE_ROLE_KEY", "SUPABASE_SERVICE_ROLE_KEY", "SECRET_KEY");
const dbUrl = pick(kv, "DB_URL", "DATABASE_URL");

const missing = Object.entries({ apiUrl, anon, service, dbUrl })
	.filter(([, v]) => !v)
	.map(([k]) => k);
if (missing.length) {
	throw new Error(
		`supabase status did not report: ${missing.join(", ")}\ngot keys: ${Object.keys(kv).join(", ")}`,
	);
}

const exported = {
	SUPABASE_URL: apiUrl,
	SUPABASE_PUBLISHABLE_KEY: anon,
	SUPABASE_SERVICE_ROLE_KEY: service,
	// the suite's global-setup terminates idle lumen_read sessions over this
	DATABASE_URL: dbUrl,
	// wrangler substitutes this for the Hyperdrive binding in local dev
	WRANGLER_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE: dbUrl,
	// The scripture live-DB harnesses assert current_user = lumen_read, so they
	// need the app role rather than the superuser. The baseline migration
	// recreates that role locally with a password matching its name.
	LUMEN_READ_DSN: dbUrl.replace(/\/\/[^@]+@/, "//lumen_read:lumen_read@"),
};

if (cmd === "env") {
	for (const [k, v] of Object.entries(exported)) console.log(`${k}=${v}`);
} else if (cmd === "write") {
	const path = join(ROOT, "apps/web/.dev.vars");
	writeFileSync(
		path,
		[
			"# Generated by scripts/local-stack.mjs — overwritten on every db:start.",
			"# Overrides the production values in wrangler.json vars for local dev.",
			`SUPABASE_URL=${apiUrl}`,
			`SUPABASE_PUBLISHABLE_KEY=${anon}`,
			"",
		].join("\n"),
	);
	console.log(`wrote ${path} → ${apiUrl}`);
} else {
	throw new Error(`unknown command: ${cmd} (expected "env" or "write")`);
}
