/**
 * personal-notes — episode index for the suggestion engine (generated from
 * lumen.entities entity_type='content_item', 2026-08-18).
 * REGENERATE when the podcast ingest adds episodes (scripts/ingest-podcast)
 * — a stale index only means new episodes miss [[ suggestions; capture from
 * the media page keeps working regardless.
 */
export const EPISODE_INDEX: ReadonlyArray<readonly [id: string, name: string]> = [
	["stick-of-joseph-FtQkqeLWY0o","\"The Doctrines and the Mysteries\" by Library of Godwin Book Launch"],
	["stick-of-joseph-NSvD6OSyiZY","A Deep Look into the Theology of Names  | Andrea W. and Dave Butler"],
	["stick-of-joseph-oNV0gr7VT_c","Abraham the Astronomer - A Presentation by Stephen Smoot | \"The Stick of Judah\" Lecture Series"],
	["stick-of-joseph-K4aU8p1F9u8","ALTARS in The LDS Temple | Todd McLauchlin"],
	["stick-of-joseph-LXoi1I_TQAk","An Evangelical's Guide to NOT Bring People to Jesus | Austin Fife & All Those in Favor"],
	["stick-of-joseph-v-QW07yO9sA","Andrea W | How the Temple is a Restoration of an Ancient Covenant"],
	["stick-of-joseph-9ZJRk8A7Uko","Andrea W. | \"I Never Knew You\" - Jesus's Most Haunting Statement"],
	["stick-of-joseph-dU81hfwml6Q","Andrea W. | The Hidden Hebrew Wedding Ritual and The Temple."],
	["stick-of-joseph-stdxxgwhcdM","Andrea W. | The Temple, The Veil, and the Bridegroom"],
	["stick-of-joseph-NH4-DqrZEa8","Are Members of the Church Dropping in Biblical Literacy? | Colton Miller & Dave Butler"],
	["stick-of-joseph-NxpBhGHQ2WY","Bible Contradictions and How the Book of Mormon Fills the Gaps | Mike & Dave"],
	["unshaken-RLirbnj-kGk","Come Follow Me - 1 Kings 12-22 - Elijah's Ministry and Miracles"],
	["unshaken-O3SiM9Yi940","Come Follow Me - 1 Samuel 17 - 2 Samuel 10 - David: From Shepherd to King"],
	["unshaken-ivzxaLpbZws","Come Follow Me - 1 Samuel 8-16 - The Rise and Fall of Saul"],
	["unshaken-6lXWLIOUKC8","Come Follow Me - 2 Kings 1-13 - Passing the Mantle"],
	["unshaken-4pSrikfJ5Yw","Come Follow Me - 2 Kings 14-25 - The Scattering of Israel"],
	["unshaken-25hrVBU3Vz8","Come Follow Me - Exodus 19-34 - Moses at Mount Sinai"],
	["unshaken-jMYk190JBys","Come Follow Me - Ruth & 1 Samuel 1-7 - Women of Faith"],
	["unshaken-8SvK7L87o1A","Come Follow Me - The Book of Joshua: Choose You This Day"],
	["unshaken-yAQlljeet-0","Come Follow Me - The Book of Leviticus: Holiness to the Lord"],
	["unshaken-ki0bTvQsaCo","Come Follow Me - The Book of Numbers: Look and Live"],
	["stick-of-joseph-VU2FtGsSL4o","Creation Through Combat - A Presentation by Trevan Hatch | \"The Stick of Judah\" Lecture Series"],
	["stick-of-joseph-ZDYw6d4PBcA","Debate Breakdown: Jacob Hansen VS. James White of @ApologiaStudios"],
	["stick-of-joseph-Rh-E4cuElj8","Dive Deeper w/ Andrea W. | Unveiling the Book of Revelation"],
	["stick-of-joseph-JM6ILq8hkyE","Dr. Chris Blythe | Ghosts in the Old Testament | The Stick of Judah Lecture Series"],
	["stick-of-joseph-cBWo0gSVCeA","Hidden Holy Days & Bring Forth the Best Robe LIVE LAUNCH EVENT"],
	["stick-of-joseph-RqqdXM5ZiVU","Hidden Meanings of Holy Week | Andrea W."],
	["stick-of-joseph-LcDCoyqsjn8","Hidden Temple Patterns Found in Isaiah's Writings | Andrea W."],
	["stick-of-joseph-87pLM-JW3gQ","How to Access the Power of Heaven Through REAL Worship | Todd McLauchlin"],
	["stick-of-joseph-KbLlsUK8P3I","How to Guard Your Heart From Failing in a Wicked World | Dive Deeper with Andrea W."],
	["stick-of-joseph-rfJCkv_JurI","How to Win the Spiritual War Being Waged on You Right Now | Todd McLauchlin"],
	["stick-of-joseph-JTPtEsp7YRE","Hugh Nibley Discovers The Ancient Endowment in Egypt | Mike & Dave Read Books"],
	["stick-of-joseph-0n5DjpJ8MJs","Jesus's Brother, Corruption in Christianity, and The Great Apostasy | Mike & Dave"],
	["stick-of-joseph-lD1grvhY4nk","Jonah Barnes Book Announcement for 2026"],
	["stick-of-joseph-vfF0opRPkjk","King Josiah, Deuteronomy, and the Book of Mormon | Mike & Dave"],
	["stick-of-joseph-fYTRLzerkQs","Mike & Dave | Oral Traditions of Isaiah Revealed"],
	["stick-of-joseph-_1arHtma-Ps","Mike & Dave | The King Follett Discourse, Joseph Smith, and Answers About God's Origin"],
	["stick-of-joseph-vi1qdSzStjY","Mike & Dave | The Ultimate Guide to Freemasonry and the Temple"],
	["stick-of-joseph-WnFgxDinydY","Mike & Dave | The Ultimate Guide to The Great Apostasy 33 AD - 383 AD"],
	["stick-of-joseph-rsuxJwfOlh4","Mike and Dave Read Books | The Cultic Prophet in Ancient Israel"],
	["stick-of-joseph-s3YjnFxSN8A","Mike and Dave Read Books | Who Wrote The Bible?"],
	["stick-of-joseph-s_uPQIw2Wi8","Palm Sunday's Ancient Symbolism | Holy Week: Day 1 with Andrea W."],
	["stick-of-joseph-xuVHCRdfQJ8","Post-Debate Breakdown with Jacob Hansen on His Masterful Defense of the Restored Gospel"],
	["stick-of-joseph-S0BmPyAGpQc","Remembering Jeffrey R. Holland's Greatest Teachings with Colton Miller"],
	["stick-of-joseph-J8fy3hItnp4","Rob Kaye | Hidden Books of Moses in the Hebrew Bible | The Stick of Judah Lecture Series"],
	["stick-of-joseph-KPq7NLgzkPk","Rob Kaye | Jew Turned Mormon On Hebrew Astronomy in Scripture"],
	["stick-of-joseph-fNsO8WJck3k","Temple Symbolism in the Parable of the Fig Tree | Holy Week: Day 3 with Andrea W."],
	["stick-of-joseph-HmT9GXDMuOA","The Ancient Meaning of 'the Serpent' is More Profound Than You Think"],
	["stick-of-joseph-4_DJy3iG2Kc","The Antichrist Playbook | A Guide For Young Saints to Avoid Deception and Defeat the Devil"],
	["stick-of-joseph-os630CTIW1I","The Divine Feminine in the Torah with Mandy Green | \"The Stick of Judah\" Lecture Series"],
	["stick-of-joseph-H-dSOTl41sA","The Documentary Hypothesis - A Presentation by Mike Day | \"The Stick of Judah\" Lecture Series"],
	["stick-of-joseph-Ot5_74i_Z5A","The Empty Tomb, Mary Magdalene, and the Feast of First Fruits | Holy Week: Day 8 with Andrea W."],
	["stick-of-joseph-yVLnswlrdLU","The First Temple, Nephi and Isaiah, and Ancient Priesthood Patterns | Mike & Dave"],
	["stick-of-joseph-HwRzz5ZN8Ac","The Hidden Meanings of the Crucifixion Scene | Holy Week: Day 5 with Andrea W."],
	["stick-of-joseph-Ilk0hJpcahY","The Key to Pulling Down the Power of Repentance | Todd McLauchlin"],
	["stick-of-joseph-K3amsJN-A40","The Missing Ministry of the Risen Christ: Live Launch Party"],
	["stick-of-joseph-63onrrP5Tz4","The Power That Holds the Universe Together | Todd McLauchlin"],
	["stick-of-joseph-HNhRCcboLDw","The Secret Identity of the Wisemen | Andrea Woodmansee"],
	["stick-of-joseph-I2AX7Mfs4Zs","The SECRET to Living the Temple Endowment Every Day | Todd McLauchlin"],
	["stick-of-joseph-iV5iicd1WiU","The True Meaning Behind Christ Cleansing the Temple | Holy Week: Day 2 with Andrea W."],
	["stick-of-joseph-nUIUwII8hCU","The True Order of Prayer and the Brother of Jared | Todd McLauchlin"],
	["stick-of-joseph-5HXbn4MotUY","Todd McLauchlin | Joseph Smith, the Lectures on Faith, and Knowing God,"],
	["stick-of-joseph-fZmLnbgD8MM","Todd McLauchlin | The Oath and Covenant of the Priesthood and its Ties to the Temple"],
	["stick-of-joseph-5q2xlK2TvMA","Top Scriptural Discoveries of 2025 with Mike & Dave"],
	["stick-of-joseph-Loxh5eIBGu8","Unveiling the Temple by Understanding the Sacred and Profane | Mike & Dave"],
	["stick-of-joseph-oE2U7tsLFZc","Val Larsen | The First Great Apostasy and the Deuteronomists | The Stick of Judah Lecture Series"],
	["stick-of-joseph-OigiFEv22OQ","What Most People Get Wrong About the Last Supper | Holy Week: Day 4 with Andrea W."],
	["stick-of-joseph-pnhTLJDAnEE","Why the Temple is MORE Than Just a Checklist Item | Andrea and Avery Woodmansee"],
];
